[package]
name = "git-note"
version = "0.1.0"
edition = "2021"
description = "An ephemeral comment extension based on Git."
license = "Apache-2.0"
include = [
    "**/*.rs",
    "Cargo.*",
    "*.md",
]

[[bin]]
name = "git-note"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["cargo", "wrap_help"] }
serde = { version = "1.0.197", features = ["derive"] }
git2 = "0.18.3"
serde_json = "1.0.115"
log = "0.4.21"
anyhow = "1.0"
sha256 = "1.5.0"
configparser = "3.0.4"
chrono = "0.4.38"
