[package]
name = "git-note"
version = "0.1.0"
edition = "2021"

include = [
    "**/*.rs",
    "Cargo.*",
    "*.md",
]

[[bin]]
name = "git-note"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["cargo", "wrap_help"] }
serde = { version = "1.0.197", features = ["derive"] }
git2 = "0.18.3"
serde_json = "1.0.115"
log = "0.4.21"
anyhow = "1.0"