use clap::{Arg, Command};

pub fn build_cli() -> Command {
    Command::new("git-note")
        .version("1.0")
        .author("cjlee38 <gptpem38@gmail.com>")
        .about("Manages personal notes on your git repository")
        .subcommand(
            Command::new("add")
                .about("Adds a new note")
                .arg(Arg::new("file")
                    .short('f')
                    .long("file")
                    .help("Specifies the file to add a note to")
                    .value_name("FILE")
                    .required(true))
                .arg(Arg::new("line")
                    .short('l')
                    .long("line")
                    .help("Specifies the line number to add a note to")
                    .value_name("LINE")
                    .required(true))
                .arg(Arg::new("message")
                    .short('m')
                    .long("message")
                    .help("The note message")
                    .value_name("MESSAGE")
                    .required(true)),
        )
        .subcommand(
            Command::new("view")
                .about("Views notes for a file")
                .arg(Arg::new("file")
                    .short('f')
                    .long("file")
                    .help("Specifies the file to view notes for")
                    .value_name("FILE")
                    .required(true)),
        )
        .subcommand(
            Command::new("edit")
                .about("Edit a note message identified by line")
                .arg(Arg::new("file")
                    .short('f')
                    .long("file")
                    .help("Specifies the file to edit a note to")
                    .value_name("FILE")
                    .required(true))
                .arg(Arg::new("line")
                    .short('l')
                    .long("line")
                    .help("Specifies the line number to edit a note to")
                    .value_name("LINE")
                    .required(true))
                .arg(Arg::new("message")
                    .short('m')
                    .long("message")
                    .help("New note message")
                    .value_name("MESSAGE")
                    .required(true)),
        )
}
