name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PROJECT_NAME: gitnote
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            command: cross
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
            command: cross
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            command: cross
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        if: matrix.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross
      - name: Build Binary
        working-directory: ./gitnote-core
        run: ${{ matrix.command }} build --verbose --locked --release --target ${{ matrix.target }}
      - name: Run tests
        working-directory: ./gitnote-core
        run: ${{ matrix.command }} test --verbose
